### ISSUE TITLE
[EPIC] Complete documentation

### ISSUE THREAD

**Issue by dwijnand** [playframework/akka-grpc-play-quickstart-scala#17]

**Comment by ignasi35** [comment]
I think we should reorganize the docs into:

1. (given a vanilla play app) how to add a gRPC Router (includes `.proto` code generator and Router binding)
1. (given a vanilla play app) how to consume a gRPC remote endpoint (includes `.proto` code generator, client binding and service discovery)
1. Running in dev mode or production
1. (when ready) deploying

Note that `.proto` code generator settings differ when creating a server or a client.

**Comment by ignasi35** [comment]
Change of plans, `1.` and `2.` are already covered in the [ref docs](https://developer.lightbend.com/docs/akka-grpc/current/play-framework.html#using-a-grpc-client-in-a-play-framework-app).

The docs on this example app should focus on `3` (https://github.com/playframework/play-scala-grpc-example/pull/27/commits/4ee92b426f638369a1ab48f329251fe56e31a29c) and `4`. Eventually, each of these two sections (running and deploying) will need moving to a more appropriate location, e.g. playframework.com.

**Comment by dwijnand** [comment]
Split off the deployment steps documentation to #30.

Fixed by #27.
