### ISSUE TITLE
Add example test code

### ISSUE THREAD

**Issue by richdougherty** [playframework/akka-grpc-play-quickstart-scala#2]
Add example test code into this project so that users can see how to test gRPC services in a Play Scala application. Depends on: https://github.com/akka/akka-grpc/issues/359.

**Comment by dwijnand** [comment]
I have a branch for this (https://github.com/dwijnand/akka-grpc-play-quickstart-scala/tree/add-example-test-code) but it's pending a fresh release of akka-grpc which includes a publish akka-grpc-play-testkit module.
