### ISSUE TITLE
Add OpenShift/Kubernetes deployment instructions

### ISSUE THREAD

**Issue by dwijnand** [playframework/akka-grpc-play-quickstart-scala#30]
(edit: by Ignasi)

 - [x] add docs on deploying on Vanilla Kuberntes #38 
 - [x] add docs on deploying on Openshift (not `minishift`)  #40

**Comment by TimMoore** [comment]
I'll edit the title. I don't think we should tie these to Lightbend Orchestration.

**Comment by ignasi35** [comment]
All done.
