### ISSUE TITLE
Document you need to 'sbt stage' first

### ISSUE THREAD

**Issue by raboof** [playframework/akka-grpc-play-quickstart-scala#4]
Following the README on a fresh checkout fails because there is no 'target' directory with alpn agent yet

**Comment by ignasi35** [comment]
There's [improvements](https://github.com/playframework/akka-grpc-play-quickstart-scala/commit/b2680c0655465e24bff9db185cc189743fa1a55d#diff-cf446b4b49425b9c58a2637d28fecb81) in `ssl-play` that make the `sbt stage` transparently and only when necessary.

**Comment by octonato** [comment]
I'm wondering why we are doing that. Wouldn't that be easier to push the APLN agent to `lib` folder, pushing it to Git and add a `.jvmopts` file with 

```
-javaagent:lib/jetty-alpn-agent-2.0.9.jar
```

That's a quickstart to let people get in touch with the tech, no? With that in mind, I would just add the necessary bit to make it work without much ado.

**Comment by dwijnand** [comment]
I'd call this resolved with Ignasi's b2680c0655465e24bff9db185cc189743fa1a55d.
