### ISSUE TITLE
Bad link, problems with doc structure

### ISSUE THREAD

**Issue by rstento** [playframework/akka-grpc-play-quickstart-scala#51]
@ignasi35, please take a look at the docs for this example, which are being published to Tech Hub. I received an email asking me to urgently fix a 404 that is appearing due to a bad link on one of the doc pages. However, when I took a look, there is more than one problem:

1) https://developer.lightbend.com/guides/play-scala-grpc-example/code-details.html, under section 2, has a link to https://developer.lightbend.com/docs/play-grpc/current/serving-grpc.html, which is a file that doesn't exist. To resolve, the link either needs to be removed or fixed, and a 301 redirect needs to be added to the Tech Hub config file. 

2) The documentation pages are not being published as a single guide. According to the source, there  six HTML pages making up one guide. Instead, the pages seem to be published singly. See:
https://developer.lightbend.com/guides/play-scala-grpc-example/ and note that there is no TOC of the other pages on the left. https://developer.lightbend.com/guides/play-scala-grpc-example/code-details.html is linked to from this page, but when you navigate to it, it does not have any way to get back to the other pages.

**Comment by rstento** [comment]
One clarification, if the page that was linked to never existed, no need to create a 301. If it did, and has been removed or renamed, yes, pls create a 301. Thnx

**Comment by ignasi35** [comment]
Thanks for the heads up @rstento !

I've fixed it here and also on the `java` version of this example.

The issue with https://developer.lightbend.com/docs/play-grpc/current/serving-grpc.html being gone is harder to fix. The `play-grpc` docs are served from techub and producing `301` may not be possible. We got some suggestions to produce redirects using [plain old HTML](https://github.com/akka/alpakka-kafka/blob/v1.0.1/docs/src/main/paradox/release-notes/1.0.html) but `play-grpc` is quite in the early stages and I don't think maintaining this redirects is worth the extra cost.

**Comment by dwijnand** [comment]
Fixed in #52.

**Comment by rstento** [comment]
Thanks for fixing, Ignasi! The file for Tech Hub to create a 301 is:
https://github.com/rstento/techhub/tree/master/src/docker/nginx/conf.d


Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Comment by ignasi35** [comment]
Hi @rstento, techhub is now fixed (uses `301`). See

https://developer.lightbend.com/docs/akka-grpc/snapshot/play-framework.html

**Comment by rstento** [comment]
Great!
Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>
